### ISSUE TITLE
[BUG] - prebuild rm -rf is not available on all platforms

### ISSUE THREAD

**Issue by NerdyChara** [BeccaLyria/discord-bot#1364]
### What bug did you encounter?

When using the npm script on Windows ; it refused to work stating "rm" is not a recognized internal or external command. 

### What did you expect to happen?

I expected a cross-platform available script. 

### Additional information

The ideal replacement in this instance would be using the "rimraf" module as a dev dependency. And then calling it in the npm script. More about it [Here](https://www.npmjs.com/package/rimraf#cli)

**Comment by naomi-lgbt** [comment]
I agree. This was something I meant to do a year ago, thought I did, and then promptly forgot about it entirely.

## Good First Issue

This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Run `npm i --save-dev rimraf` to install the dependency.
- Update the `prebuild` script to `rimraf ./prod`.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by ardasevinc** [comment]
Hello! I'm interested in this issue

**Comment by naomi-lgbt** [comment]
Go for it!
