### ISSUE TITLE
[BUG] - Link detection doesn't work properly

### ISSUE THREAD

**Issue by Panquesito7** [BeccaLyria/discord-bot#1809]
### What bug did you encounter?

In my case, I allowed `hashnode.dev` links to be sent to the server. However, if someone uses something such as `<username>.hashnode.dev`, Becca will detect it as another completely different link and the message will be blocked.

### What did you expect to happen?

The message containing the link shouldn't be blocked.

### Screenshots

![image](https://github.com/BeccaLyria/discord-bot/assets/51391473/e41ad2df-7ce3-4a08-bf90-55892eb887db)

**Comment by naomi-lgbt** [comment]
Ahhh, I think I see the issue. Because you've allowed `hashnode` **and** `hashnode.dev`, it saw two allowed link matches, and one blocked link message.

https://github.com/BeccaLyria/discord-bot/blob/faee621c3e8c47db9c69b05c229d48880b09fa24/src/listeners/automod/automodLinks.ts#L55

And since they check for equality, it triggered.

Thankfully a quick fix - the linked line above would need to change to `blockedLinks > allowedLinks`.

**Comment by naomi-lgbt** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by naomi-lgbt** [comment]
Sure! Have fun! 😁

**Comment by Lokendrakushwah12** [comment]
I made the changes can you please review it
