### ISSUE TITLE
[FEAT] random fortune cat gif embed for fortune command

### ISSUE THREAD

**Issue by starlightknown** [BeccaLyria/discord-bot#605]
# Feature Request

## Is your feature request related to a problem? Please describe:
Not a problem but since Becca's commands have cats and fortune, we can embed random fortune related gifs which will make it more fun.
## Describe the solution you'd like
Example gif - [fortune cat gif](https://giphy.com/gifs/cat-clover-catgrass-hqxYKGRA43R7WKTUNs)
Create a whole list of such gifs and make it random along with the fortune.

**Comment by nhcarrigan** [comment]
This is a great idea!

I think the best approach would be to store the gifs in the repository and use them locally, to avoid image links breaking in the future.

We'd want to create a folder containing the gifs, generate an array of the gif file names, and randomly select one from that array in the `fortune` command - then, instead of a raw text message, the `fortune` command should be modified to send an embed with the fortune text as the `description` value and the image as an attachment.

**Comment by starlightknown** [comment]
Yep and I haven't thought about link breaking, I should update this in my bot too. Great idea, thank you!

**Comment by Vyvy-vi** [comment]
Would hosting the images on the cdn be a good option?

**Comment by nhcarrigan** [comment]
Yep that would be a solid approach too.

**Comment by nhcarrigan** [comment]
Going to close this as Becca is going in a bit of a different direction lately.
