### ISSUE TITLE
[FEAT] - Command Ticket

### ISSUE THREAD

**Issue by qwel-exe** [BeccaLyria/discord-bot#848]
### What feature would you like to see?

We should create a new emote command - this can be a subcommand of /becca.

This command should make a New Ticket

Features:
* New Ticket
* Close Ticket
* Delete
* Remove

### Additional information
idea for hacktoberfest

**Comment by nhcarrigan** [comment]
I'll need to put some thought in to how I want to implement this.

**Comment by qwe123coder** [comment]
> I'll need to put some thought into how I want to implement this.

hey ig ik how to do it if you assign to me also we both could do it together

**Comment by nhcarrigan** [comment]
It's not just about knowing how to write the code, but also how I want to fit the feature in to the infrastructure. 🙂

**Comment by qwe123coder** [comment]
> It's not just about knowing how to write the code, but also how I want to fit the feature in to the infrastructure. slightly_smiling_face

:)

**Comment by qwe123coder** [comment]
> It's not just about knowing how to write the code, but also how I want to fit the feature in to the infrastructure. slightly_smiling_face

hey I was also thinking about adding  few games to becca what do you tell on this

**Comment by nhcarrigan** [comment]
You're welcome to open issues to propose new features. :)

**Comment by L0SER8228** [comment]
I would like to do that, but can you please explain what does `remove`, `delete` command expected to do

**Comment by nhcarrigan** [comment]
As mentioned above, the implementation for this hasn't been assessed yet so this one is not quite open for contribution.

**Comment by L0SER8228** [comment]
One more things is, there is threads which is better than tickets , I think so
We can do something with threads just like ticket system
create thread, close, archive

**Comment by nhcarrigan** [comment]
The problem with threads is that private threads require boost level 2. Most ticket systems create private channels to allow the user to speak with the team about more confidential information.

**Comment by L0SER8228** [comment]
Oh Idk that,

**Comment by qwe123coder** [comment]
so remove 
Removes a member to a specified ticket

**Comment by qwe123coder** [comment]
add
Adds a member to a specified ticket.
like a co-member included in the incident

**Comment by qwe123coder** [comment]
close 
Closes the ticket.

**Comment by qwe123coder** [comment]
delete 
Delete a specified ticket

**Comment by qwe123coder** [comment]
open
Re-opens a ticket.

**Comment by qwe123coder** [comment]
new 
Creates a new ticket.

**Comment by qwe123coder** [comment]
hope this helps 
@L0SER8228 @nhcarrigan

**Comment by L0SER8228** [comment]
I understand, is anyone working on it, otherwise I would like to do

**Comment by qwe123coder** [comment]
oh no one @nhcarrigan could assin to you

**Comment by L0SER8228** [comment]
One more thing, it would be better if we create subCommand of `/ticket` instead of `/becca`
`/ticket create`, `/ticket close`, `/ticket add`, `/ticket remove`, `/ticket remove`, `/ticket delete`

**Comment by nhcarrigan** [comment]
Nope. That's not the route I think I want to go.

Here's my planned implementation approach:

Add 2 new configuration settings:
- `ticket category` to set where new ticket channels are created.
- `ticket role` to set which role gets added to the ticket.

Create a new `/community ticket` command. This command will first check if the two new configs are set. If they are not, Becca responds with a message that the server has not enabled the ticket system. Otherwise:
Becca creates a new channel under the `ticket category` with the name `ticket-${interaction.user.username}`. Becca sets the permissions to `@everyone` cannot view the channel, `interaction.user.username` and `ticketRole` can (and herself, too).
The ticket command will need to take a `reason` option (as string), which is the user's reason for opening the ticket. Becca will add that to an embed as `description`, with the title being `${interaction.user.username}'s ticket` and the author being set to the user. Becca will send that embed as the first message in the ticket channel, attaching a `close` button to it that allows someone to close the ticket. Giving the button a `customId` set to `close-ticket` will allow us to add that in the `interactionCreate` logic to listen for. If the button is clicked, delete the channel.

**Comment by L0SER8228** [comment]
That's also good, besides thanks for this explanation. It will help me create those commands

**Comment by nhcarrigan** [comment]
All yours.

Note that PRs opened before October 1st will not count for Hacktoberfest.

If you have any questions about the contributing process, we recommend joining [our support server](https://chat.nhcarrigan.com)

**Comment by L0SER8228** [comment]
Hey, one question
If the close button, delete the ticket, then we no longer need the delete Comamnd right ? Delete and close are same?

**Comment by nhcarrigan** [comment]
Correct. We only need one command: `/community ticket`.

The button will handle the close action. No other actions are needed.

**Comment by L0SER8228** [comment]
He asked for a `add` and `remove` command?

**Comment by nhcarrigan** [comment]
Those are not planned in our intended implementation. You should follow the outline here: https://github.com/BeccaLyria/discord-bot/issues/848#issuecomment-930347557

**Comment by L0SER8228** [comment]
Hey I need some help, how to get the guild database. I need to check if `ticket role` and `ticket category` is set or not

**Comment by nhcarrigan** [comment]
The guild data is represented by [`ServerModel.ts`](https://github.com/BeccaLyria/discord-bot/blob/main/src/database/models/ServerModel.ts) and is available in the [`community` commands](https://github.com/BeccaLyria/discord-bot/blob/main/src/commands/community.ts) as `config`, which you would pass into your `handleTicket.ts` file.

**Comment by nhcarrigan** [comment]
Heya @L0SER8228,

Just checking in to see if you are still working on this.

**Comment by naomi-lgbt** [comment]
I am moving this discussion over to #1370 to clarify the planned implementation.
